spring:
  application:
    name: cadastros
  datasource:
    drive-class-name: org.postgresql.Driver
    password: 1234567
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
